// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUxwqjfuHqMEDXWOPxSeIbYKlTheiODCk',
    appId: '1:32553696651:web:71b11fd12b8569387ac38e',
    messagingSenderId: '32553696651',
    projectId: 'flaschat-1f68f',
    authDomain: 'flaschat-1f68f.firebaseapp.com',
    storageBucket: 'flaschat-1f68f.appspot.com',
    measurementId: 'G-PS5L6QF0PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYlnpyu3poo-SD3lmvc5yLgpZGYWCFWA',
    appId: '1:32553696651:android:6262b47751064e957ac38e',
    messagingSenderId: '32553696651',
    projectId: 'flaschat-1f68f',
    storageBucket: 'flaschat-1f68f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_sum9S8tfmpjGTEs14T9yYoGZN32HFs',
    appId: '1:32553696651:ios:2b423239804c38457ac38e',
    messagingSenderId: '32553696651',
    projectId: 'flaschat-1f68f',
    storageBucket: 'flaschat-1f68f.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_sum9S8tfmpjGTEs14T9yYoGZN32HFs',
    appId: '1:32553696651:ios:2b423239804c38457ac38e',
    messagingSenderId: '32553696651',
    projectId: 'flaschat-1f68f',
    storageBucket: 'flaschat-1f68f.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUxwqjfuHqMEDXWOPxSeIbYKlTheiODCk',
    appId: '1:32553696651:web:728b2ff1e001b2e37ac38e',
    messagingSenderId: '32553696651',
    projectId: 'flaschat-1f68f',
    authDomain: 'flaschat-1f68f.firebaseapp.com',
    storageBucket: 'flaschat-1f68f.appspot.com',
    measurementId: 'G-GHEX0N6EYV',
  );
}
